config/routes.rb
Rails.application.routes.draw do
  get 'dashboard' => 'admin_dashboard#index'

  get 'dashboard/show/:project_id' => 'admin_dashboard#show'

  devise_for :users
  resources :projects

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jomlaunch</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
      <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand topnav" href="/">Jom Launch</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="/#about">About</a>
            </li>
            <% if user_signed_in? == false %>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">Login</a>
                <div class="dropdown-menu" style="padding:17px; min-width:230px">
                  <%= bootstrap_form_for(:user, :url => session_path(:user)) do |f| %>
                    <%= f.text_field :email, hide_label: true, placeholder: "Email"  %>
                    <%= f.password_field :password, hide_label: true, placeholder: "Password"  %>
                    <%= f.check_box :remember_me %>
                    <%= f.submit 'Sign in' %> 
                    <hr>
                    <%= link_to "Forgot your password?", new_password_path(:user) %>
                  <% end %>
                  <a href="/users/sign_up">Sign up</a>
                </div>
              </li>
            <%else%>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  <%=current_user.email%> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <%= link_to("Your projects", projects_path) %>
                  </li>
                  <li>
                    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                  </li>
                  <li>
                    <%= link_to "Edit", edit_user_registration_path%>
                  </li>
                </ul>
              </li>
            <%end%>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
          <!-- /.container -->
    </nav>


    <div  style="padding-top: 50px"></div>
    <div class="wrapper">
      <div class="container">
        <% if notice.nil? == false %><p class="alert alert-success"><%= notice %></p><% end %>
        <% if alert.nil? == false %><p class="alert alert-danger"><%= alert %></p><% end %>
      </div>  
      	<%= yield %>
         
    </div>
    <div style="padding:50px"></div>

    <!-- Footer -->
    <div class="col-xs-4 col-xs-offset-4 footer" >
      <div class="row">
        <div class="col-lg-12">
          <div class="sponsor text-center" ><%= image_tag("JOM.png", :align=> "bottom") %><%= image_tag("training_my.png", :align=> "bottom") %><%= image_tag("terrato.png", :align=> "bottom") %></div>
          <hr class="intro-divider">
          <ul class="list-inline">
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <p class="copyright text-muted small">Copyright &copy; JomLaunch 2015. All Rights Reserved</p>
            </li>
          </ul>
        </div>
      </div>
    </div>
</html>